version: '3.4'
volumes:
  mysql-volume:
    name: blazorapp-mysql-volume

networks:
  mysql_net:
    driver: bridge


services:
  blazorapp-mysql:
    image: mysql
    container_name: blazorsql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    networks:
      mysql_net:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: blazorapp-mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: supersecret
    ports:
      - 8060:80
    depends_on:
      - blazorapp-mysql
    networks:
      mysql_net:

  blazorapp:
    # image: blazorapp
    container_name: blazorapp
    build:
      context: .
      dockerfile: app/Dockerfile
    depends_on:
      - phpmyadmin
      - blazorapp-mysql
    networks:
      mysql_net:
    ports:
      - 5000:80
      - 5001:443

